### ISSUE TITLE
Violating Redux Principles

### ISSUE THREAD

**Issue by ghost** [jakeowns/react-live-graph#1]
It looks like you're violating at least two Redux principles. Firstly you don't have a single source of truth. The DataTable class owns a state while there is also state in the store. Secondly you are using setState(). Instead of setState(), simply dispatch an action. Maybe you didn't catch these issues because you didn't originally start with Redux from the beginning of the project.

**Comment by jakeowns** [comment]
The state of the input fields in the DataTable component were not meant to be shared in a global context, therefore it was kept in local state. Refer to the following issue discussing when to use Redux store or React state.
https://github.com/reactjs/redux/issues/1287#issuecomment-175351978

**Comment by ghost** [comment]
I understand there are some use cases for a "local" state and Redux in the same app. I'm curious as to why you think you need a "local" state though.
